model_name: multilayer_lstm_ctc
corpus:
    name: digits
    label_type: numbers
feature:
    name: mfcc
    num_context: 4
    num_features: 13
hyperparameter:
    num_classes: 28 #ord('z') - ord('a') + 1(space) + 1(blank) + 1
    num_hidden: 100
    num_layers: 3
    batch_size: 8
    num_epoches: 100
    optimizer: Adam
    learning_rate: 0.9
    weight_init: 0.1
    clip_grad: 5.0
    clip_activation: 50
    dropout_input: 0.8
    dropout_hidden: 0.5
path:
    tensorboard_logs: ../tensorboard
    train_directory:  ../audio_numbers
