model_name: multilayer_lstm_ctc

corpus:
    name: digits
    label_type: numbers

feature:
    name: mfcc
    input_size: 123
    splice: 0
    num_stack: 1
    num_skip: 1
    num_context: 9
    num_features: 9

hyperparameters:
    num_cell: 100
    num_proj:
    num_layer: 5
    batch_size: 64
    optimizer: adadelta
    learning_rate: 0.9
    num_epoch: 50
    weight_init: 0.1
    clip_grad: 5.0
    clip_activation: 50
    dropout_input: 0.8
    dropout_hidden: 0.5