model_name: multilayer_lstm_ctc
dataset:
    name: digits
    label_type: numbers
    lang: ENG
    dataset_path: ./audio_numbers
feature:
    name: mfcc
    feature_size: 13
    num_context: 4
hyperparameter:
    num_classes: 28 #ord('z') - ord('a') + 1(space) + 1(blank) + 1
    num_hidden: 100
    num_layers: 2
    batch_size: 8
    num_epoches: 150
    optimizer: Adam
    learning_rate: 0.9
    weight_init: 0.1
    clip_grad: 5.0
    clip_activation: 50
    dropout_prob: 1
model:
    tensorboard_path: ./tensorboard_two_layers_digits
    model_path:  ./trained_models/digit
