model_name: multilayer_lstm_ctc
corpus:
    name: digits
    label_type: numbers
    lang: ENG
feature:
    name: mfcc
    num_context: 4
    num_features: 13
hyperparameter:
    num_classes: 28 #ord('z') - ord('a') + 1(space) + 1(blank) + 1
    num_hidden: 100
    num_layers: 2
    batch_size: 8
    num_epoches: 150
    optimizer: Adam
    learning_rate: 0.9
    weight_init: 0.1
    clip_grad: 5.0
    clip_activation: 50
    dropout_input: 1
    dropout_hidden: 1
path:
    tensorboard_logs: ./tensorboard_two_layers_digits
    train_directory:  ./audio_numbers
    trained_model:  ./trained_models/digit
